
cc_library(
    name = "os",
    srcs = [
        "Compat.cpp",
        "FileSystem.cpp",
        "OS.cpp"
    ],
    deps = [
        "//:include-god",
        "@com_github_gflags_gflags//:gflags",
        "@com_github_google_glog//:glog",
        "@llvm-project//llvm:Core",
    ]
)
 
