# load(":helper.bzl", "helper")

# helper("x86", 32, 0, 0)
# helper("x86_avx", 32, 1, 0)

# helper("amd64", 64, 0, 0)
# helper("amd64_avx", 64, 1, 0)

# cc_test(
#     name = "x86_test",
#     srcs = ["testembed1_test.cc"],
#     deps = [
#         ":testembed1",
#         "@com_google_googletest//:gtest_main",
#     ],
# )